### ISSUE TITLE
The provided script "steamos-session" prevents the actual steamos session to start

### ISSUE THREAD

**Issue by dubigrasu** [alkazar/steamos-compositor#1]
This is on SteamOS Brewmaster 2.0

The starting script hangs at the "bluetoothctl power on" command (line 23).
Not sure if the command should behave in a certain way and let the script to continue or is just a typo.
In any case, an "&" after the respective line allows the script to continue and steamos session to start.

**Comment by alkazar** [comment]
If you run `bluetoothctl power on` in a terminal, what happens? What about `sudo bluetoothctl power on`? And what is the output of `systemctl status bluetooth`?

I don't think the command is actually necessary on SteamOS, but was required for me on Arch to get bluetooth controllers to work.

Also, how did you install this on SteamOS?

**Comment by alkazar** [comment]
Well, I found at least one reason this could happen: if the bluetooth service is not running. I have created a branch to fix this called `bluetooth-fix`. Could you see if that branch fixes things for you?

**Comment by dubigrasu** [comment]
Apologies for the late response.
You're right that the script fails because the bluetooth service is not running.
The "bluetoothctl power on" command is causing no response (other than displaying: [bluetooth]#), while "systemctl status bluetooth" reports the service as inactive (dead). Which I suppose is normal since my motherboard has no built-in bluetooth capabilities.

However, if I insert an USB bluetooth adapter, the bluetooth service is automatically started, "bluetoothctl power on" command lists my available external bluetooth devices, and the steamos-session doesn't fail this time.

As for the "bluetooth-fix" branch, yes, that one is working regardless if I have the bluetooth USB inserted or not/bluetooth service active or dead.

The installation was done by compiling from the source and copying the necessary files.

**Comment by alkazar** [comment]
Merged and released. Thank you for reporting and testing!
