### ISSUE TITLE
[Help] Start the session from xinit

### ISSUE THREAD

**Issue by PapyElGringo** [alkazar/steamos-compositor#14]
Im trying to start the session from nvidia-xrun xinit file to be able to start steamos under my nvidia GPU. 

Im not sure what to exec.. Can you guide me?

**Comment by alkazar** [comment]
You just need to run the command `steamos-session`.

**Comment by PapyElGringo** [comment]
Ok I tryed before and Xorg failed to start correctly while it's start fine from GDM. I thought it's wasn't the correct why to do it. I'll need to investigate why it's fail from nvidia-xrun

**Comment by PapyElGringo** [comment]
After investigating a bit It's seem that it's steam that crash...
Here is the bin.
https://0bin.net/paste/usIxBBnDRQ7Qc9Ow#d0CyxWDT2J701coswx+RSZCaFXeB-R8xObbpULuNOwk

Any idea?

**Comment by alkazar** [comment]
"libGL error: failed to load driver: swrast"

Looks Steam is not picking up OpenGL drivers correctly. It is falling back to software rendering, but even that is failing.

I am not familiar with nvidia-xrun, but it seems something is not configured correctly. Perhaps try running a simple test app like glxgears with it first?

**Comment by PapyElGringo** [comment]
I missed the lib-32-nvidia-utils library
 Working fine now !
Thanks
