### ISSUE TITLE
Enable mangohud by default

### ISSUE THREAD

**Issue by alkazar** [alkazar/steamos-compositor#17]
- run Steam with mangohud if available
- hide hud on startup
- change hotkey to F3 in order to avoid conflict with Steam screenshot hotkey

**Comment by alkazar** [comment]
I tried running Steam with mangohud. It does work in big picture mode, but the hud disappears when you run a game. Mangohud appears briefly when you get a Steam toast message (such as when taking a screenshot), but disappears when the toast disappears and is also positioned relative to the toast.

The only other way to implement this would be to set the launch options of EVERY game in Steam, but that doesn't seem like a good idea.

I don't think this is possible to implement. Users will have to edit the launch options for the games they wish to enable mangohud on.

**Comment by alkazar** [comment]
Ended up implementing this, but only for Vulkan using some environment variables.

**Comment by alkazar** [comment]
There was a suggestiong that using `LD_PRELOAD` we might be able to enable mangohud for all OpenGL apps as well. However, adding `export LD_PRELOAD=/usr/lib/libMangoHud.so:/usr/lib32/libMangoHud.so` to `/usr/bin/steamos-session` resulted in Steam crashing.
Using just `export LD_PRELOAD=/usr/lib/libMangoHud.so` allowed Steam to run with mangohud displaying, but any games I launched would immediately crash.

**Comment by daniel-j** [comment]
MangoHud is not compatible with Proton 5.13. Uninstalling MangoHud and removing the env vars makes Proton launching again.
