### ISSUE TITLE
Modifying 'steam-compositor-plus' file doesnt change resolution or refresh rate

### ISSUE THREAD

**Issue by thesingerdenelle** [alkazar/steamos-compositor#19]
I've been trying to change the refresh rate of my monitor at 4k. Currently it doesnt change when I make changes to the compositor config file. I've tried to change resolution as well to no avail. Anything I may be missing?

**Comment by thesingerdenelle** [comment]
Im not sure what the best way would be to post the contents of the file on here as I wouldnt call myself super proficient with linux and Github. Basically, I have added "2560x1440" to the 'GOODMODES' line and have kept 'GOODRATES' as the default '60.0' and '59.9'. My issue is that while I get a full 4k image, the refresh rate defaults to 30hz for some reason. The monitor which is my Sony Bravia is 4k 60hz capable. Have used it for gaming on windows with no issues. 

As per your questions:

1. The resolution is correct, but the refresh rate is definitely 30hz

2. Definitely certain my monitor supports that resolution/refresh rate combination. 

So having a look through `~/set_hd_mode.log` I can see that 3840x2160 at 60hz doesnt seem to be available for some reason? The card I'm using is an AMD RX 5700XT. I might have to try a different monitor to make sure. Is it possible to add undetected resolutions/framerates? 

Thanks for your help and love the work you're doing on 'GamerOS'. Really grateful for an up to date alternative to Steam OS! 💯

**Comment by thesingerdenelle** [comment]
Is it possible to add undetected resolutions/refresh rates?

**Comment by alkazar** [comment]
Hmm. Not sure, but perhaps you need a different cable. Are you using HDMI? Some cables can't support more than 4k @ 30Hz.

**Comment by thesingerdenelle** [comment]
Yeah I am using HDMI, the cable works fine at 4K 60hz when using windows so I’m not entirely sure. I’ll try a different cable anyway and see if that makes a difference, thanks again!

**Comment by francis-chiew** [comment]
I am having a similar problem.
I've set `~/.config/steamos-compositor-plus` to
> #GOODMODES=("1920x1080")

But alas. Still stuck with 3840x2160 as my resolution. 
Steam scales fine, but a lot of games do not.
I've attached the `set_hd_mode.log` file. In looking at it, it seems to me that it thinks it is setting the resolution to 1920x1080, but the TV reports otherwise.
[set_hd_mode.log](https://github.com/gamer-os/steamos-compositor-plus/files/4677167/set_hd_mode.log)

**Comment by sharkwouter** [comment]
Could you try removing the # before GOODMODES?

**Comment by francis-chiew** [comment]
-_-
Thanks. Can't believe I didn't think to remove the comment tag.
Works fine now :)
