### ISSUE TITLE
[Request] Add ability to specify running resolution

### ISSUE THREAD

**Issue by ShadowApex** [alkazar/steamos-compositor#2]
Right now `set_hd_mode.sh` will automatically select the 4k resolution if it is available. It would be nice if we could specify this feature using a command-line argument to force a particular resolution.

For some context, I have been experimenting with [Steam Link Anywhere](https://steamcommunity.com/app/353380/discussions/0/3362406825533023360/) to stream Steam games over the internet. Streaming at 4k resolution makes it much more prone to network bandwidth/latency.

**Comment by alkazar** [comment]
Not sure what would be best here. Perhaps moving GOODMODES into a separate config file?

For now you could remove the 3840x2160 option from GOODMODES.

Ideally, are you wanting to change resolution back and forth at will from within big picture mode?

There are also streaming options on the host and client to restrict the resolution, not sure if that would help with the lag.

**Comment by ShadowApex** [comment]
@alkazar 

> Not sure what would be best here. Perhaps moving GOODMODES into a separate config file?

I think moving them into a separate configuration file would be good. Maybe check for the existence of `$HOME/.steamosrc` or something similar for environment variables that can be overridden. 

I've manually changed the `set_hd_mode.sh` script, but it would be nice if it didn't require editing the script, as those changes could get wiped out when updating through AUR.

> Ideally, are you wanting to change resolution back and forth at will from within big picture mode?

This would definitely be ideal, but I'm not sure how this could be done. Maybe having a standalone "Configuration" app that you could launch from Big Picture Mode written with SDL2 that could handle making these kinds of changes?

> There are also streaming options on the host and client to restrict the resolution, not sure if that would help with the lag.

I did see these, but I'm honestly not sure if it has to do some additional transcoding work to stream with the resolution set at 4k. I might try doing some testing to see if the resolution has any effect on streaming latency.

**Comment by ShadowApex** [comment]
An example implementation of using a config from `set_hd_mode.sh` might be:

**set_hd_mode.sh**
```bash
...
GOODMODES=("3840x2160" "1920x1080" "1280x720")
GOODRATES=("60.0" "59.9")

# Override the defaults from the user config
if [ -f "$HOME/.steamosrc" ]; then
    source "$HOME/.steamosrc"
fi
...
```

**Comment by alkazar** [comment]
> This would definitely be ideal, but I'm not sure how this could be done. Maybe having a standalone "Configuration" app that you could launch from Big Picture Mode written with SDL2 that could handle making these kinds of changes?

Yes, that is what I was thinking. Some kind of big picture interface for xrandr. Out of scope for this project, but could definitely be something to consider for gamerOS in the future.

If you are going to go as far as posting code, why not make a PR? :wink:

**Comment by ShadowApex** [comment]
> If you are going to go as far as posting code, why not make a PR? wink

Will do!

**Comment by alkazar** [comment]
Thanks for the PR! Merged.
