### ISSUE TITLE
Is it possible to set/move set_hd_mode.log to something that isn't the home directory

### ISSUE THREAD

**Issue by RlndVt** [alkazar/steamos-compositor#21]
Is it possible to set/move set_hd_mode.log to something that isn't the home directory

Would suggest something under XDG_CACHE_HOME (~/.config/steam-os-compositor-plus/set_hd_mode.log ?)

**Comment by alkazar** [comment]
Good idea, this can be annoying. It is a relic of the original Steam compositor which was meant only for use on Steam machines.

**Comment by sharkwouter** [comment]
It should probably follow the XDG standard and use th XDG_DATA_DIR

**Comment by alkazar** [comment]
The XDG spec is unclear in the case of log files, but I would be inclined to use the cache directory.

**Comment by infection-tag** [comment]
So, you want to move a file from one dir to another?

**Comment by Samsagax** [comment]
This issue is solved by #31 that was already merged. Should be closed.

**Comment by alkazar** [comment]
Well, technically the file is still in the home directory...

**Comment by Samsagax** [comment]
> Well, technically the file is still in the home directory...

Yeah. But most "root" logs are in home directory like `.xsession-errors` and such that are hidden but readily accessible. Maybe hiding it is enough for the intended purpose. (Until the Freedesktop specification includes `.var` directory, that is)

**Comment by alkazar** [comment]
Okay, closing. If the current solution doesn't work for someone, they can file a new ticket I suppose.
