### ISSUE TITLE
Add support for switching between multiple displays

### ISSUE THREAD

**Issue by gabrielraphael** [alkazar/steamos-compositor#22]
I using a notebook with compromised screen I can run the system open the big picture but it not displaying on the external monitor , the bios are configured to use the external vga as main monitor. 

I tried the answers  (change grub etc.. ) I did not found any of this to change.

Someone find a way to change it?

thanks

**Comment by alkazar** [comment]
This should now be possible in ChimeraOS 25 by pressing super + p

**Comment by Vegas10128** [comment]
> This should now be possible in ChimeraOS 25 by pressing super + p

New to ChimeraOS, which button would "super" be on a windows keyboard?

**Comment by Samsagax** [comment]
> New to ChimeraOS, which button would "super" be on a windows keyboard?

Please don't necro-post old issues. The Super key is the one between the ALT and CTRL key labeled with a Windows logo.
