### ISSUE TITLE
Steam Overlay and popups appear as white featureless boxes.

### ISSUE THREAD

**Issue by ghost** [alkazar/steamos-compositor#23]
When pressing shift-tab, and when notifications such as friends starting games appear, they're only a white box, with no text or visible content.

**Comment by rshamsnejad** [comment]
Thanks for the report. This issue is already logged here : https://github.com/gamer-os/gamer-os/issues/112

Can you post here, detailing which GPU you have ?

**Comment by alkazar** [comment]
Closing in favour of gamer-os/gamer-os#112 for now.

The issue was introduced in a Steam update, not sure if there is anything that can be done in the compositor.
