### ISSUE TITLE
steamos-compositor interferes with Kodi's 24fps playback

### ISSUE THREAD

**Issue by ChojinDSL** [alkazar/steamos-compositor#24]
I've noticed that when I play media content encoded with 24fps, e.g. most movies and modern TV shows, there is a slight irregular stutter every couple of seconds. Most noticeable during camera pans. I definitely didn't have this on a pure Ubuntu + Kodi install. 

I've noticed that if I use steambuddy to toggle the compositor, then the problem goes away and playback is pretty much perfect as far as I can tell.

Is there a way to edit the launch command for kodi so that the compositor gets turned off when launching kodi, and turned back on when exiting kodi?

Has anyone else experienced this?

**Comment by alkazar** [comment]
BPM and steamos-compositor-plus are no longer supported.
