### ISSUE TITLE
Replace this compositor with the gamescope compositor

### ISSUE THREAD

**Issue by YottaBiter** [alkazar/steamos-compositor#25]
Basically [gamescope](https://github.com/Plagman/gamescope) is a Vulkan + Wayland compositor being worked on by @Plagman.

**Comment by alkazar** [comment]
Sorry, we can't use gamescope yet by default.
Gamescope is actually included in GamerOS but not enabled by default.
One big problem is gamescope does not work with Nvidia GPUs.
You can try it out by installing gamescope and modifying the COMPOSITORCMD variable in the configuration file.
