### ISSUE TITLE
[Bug] Window focus constantly switches between launcher and game for Elder Scrolls Online

### ISSUE THREAD

**Issue by ShadowApex** [alkazar/steamos-compositor#3]
When running The Elder Scrolls Online using Proton, three windows are created after launch:

* The game launcher
* The game launcher system tray icon
* The game window itself

After getting past the launcher, the game launches normally, but will constantly switch back and forth between the game launcher and the game itself. One workaround I've used is to manually kill the launcher process from the command line. 

We might want to consider focusing the largest window or the most newly created window. This issue may also effect other games that use launchers that run in the background.

**Comment by alkazar** [comment]
Is the behaviour the same when running the compositor with the `-b` option? i.e. is this the same behaviour as the standard steam os compositor?

**Comment by ShadowApex** [comment]
@alkazar Yes, this behavior exists in the standard steamos compositor. So it occurs with both disabling or enabling the game focus hack.

**Comment by alkazar** [comment]
Interesting. Shouldn't be too hard to fix.

**Comment by alkazar** [comment]
I have created a branch that might fix this (I don't have any game that I know of that exhibits this issue). Please try compiling and testing with Elder Scrolls Online.

The branch is: https://github.com/alkazar/steamos-compositor/tree/multiple-game-window-fix

**Comment by ShadowApex** [comment]
These are the logs from running with that branch:
```bash
ERROR: ld.so: object '/usr/lib32/libmodeswitch_inhibitor.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
error 9: BadDrawable (invalid Pixmap or Window parameter) request 143 minor 1 serial 123
error 9: BadDrawable (invalid Pixmap or Window parameter) request 143 minor 1 serial 232
error 9: BadDrawable (invalid Pixmap or Window parameter) request 143 minor 1 serial 267
error 9: BadDrawable (invalid Pixmap or Window parameter) request 143 minor 1 serial 285
error 9: BadDrawable (invalid Pixmap or Window parameter) request 143 minor 1 serial 1275
focused id: '0x1400014', new id: '0x60006e', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x1400025', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x140002b', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x1400031', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x1400037', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x140003d', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x1400043', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x1a00008', focused gameID: '0', new gameID: '306130', reset focus: no
focused id: '0x1400014', new id: '0x1a00008', focused gameID: '0', new gameID: '306130', reset focus: no
focused id: '0x1a00008', new id: '0x2400005', focused gameID: '306130', new gameID: '306130', reset focus: yes
focused id: '0x2400005', new id: '0x2800001', focused gameID: '306130', new gameID: '306130', reset focus: yes
focused id: '0x2800001', new id: '0x1a00001', focused gameID: '306130', new gameID: '306130', reset focus: yes
focused id: '0x1400014', new id: '0x260008b', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x260008b', focused gameID: '0', new gameID: '0', reset focus: yes
focused id: '0x1400014', new id: '0x2800001', focused gameID: '0', new gameID: '306130', reset focus: no
focused id: '0x1400014', new id: '0x1a00001', focused gameID: '0', new gameID: '306130', reset focus: no
focused id: '0x2800001', new id: '0x1a00001', focused gameID: '306130', new gameID: '306130', reset focus: yes
```

This is the script I'm using as a workaround, which kills the "Launcher" after starting the game:
```bash
#!/bin/bash
WINDOW_ID=$(env DISPLAY=:0 XAUTHORITY=/home/steam/.Xauthority xwininfo -root -children | grep Launcher | awk '{print $1}')
env DISPLAY=:0 XAUTHORITY=/home/steam/.Xauthority xkill -id "${WINDOW_ID}"
```

**Comment by alkazar** [comment]
I have updated the branch. Elder scrolls online is working now. However, this breaks at least one other game: mirror's edge.

Also, exiting elder scrolls online leaves you stuck at the steamos loading bars screen indefinitely. It looks like the launcher never exits and is no longer visible.

Might have to rethink the solution.

**Comment by alkazar** [comment]
There is now a work around if you also run Steam Buddy (or use GamerOS). There is a toggle in the Steam Buddy UI to turn the steamos compositor off. It is replaced with openbox allowing you to alt tab or select different windows. Not great, but it is something.

**Comment by brain-anti-freeze** [comment]
I don't have the game to test it but these changes may help #28

**Comment by Samsagax** [comment]
Since #28 is merged. Is this still relevant?

**Comment by alkazar** [comment]
I don't think #28 relates to this issue.

**Comment by alkazar** [comment]
This should be fixed in the latest steamos-compositor-plus. Window selection is now stabilized and selects the newest window.
