### ISSUE TITLE
Fedora Installation

### ISSUE THREAD

**Issue by massatt212** [alkazar/steamos-compositor#39]
is it possible to install on fedora?

**Comment by sharkwouter** [comment]
Try the building from source instructions. Those should work on Fedora.

**Comment by massatt212** [comment]
nothing happens when i try building it manually, ill try again and show you what happens|
I built it and and tried to install but nothing happens.

**Comment by massatt212** [comment]
i swapped to Manjaro
but when i play origin games the origin launcher puts the game in the background, Titanfall.
