### ISSUE TITLE
Request or Question

### ISSUE THREAD

**Issue by massatt212** [alkazar/steamos-compositor#41]
Is their a way to disable all windows app going fullscreen, the scaling of some apps looks really terrible, the games with launcher like origins uplay and shortcuts from epic games.

**Comment by alkazar** [comment]
That is the whole point of using the SteamOS compositor, to make a more console-like experience. Put simply, those games/launchers are not compatible with a console experience and should be played on a desktop computer.

You can temporarily switch to a more traditional window manager by selecting "Toggle Compositor" from the gear menu in the Steam Buddy web app.
