### ISSUE TITLE
Gamscope with Steamos compoitor-plus

### ISSUE THREAD

**Issue by massatt212** [alkazar/steamos-compositor#46]
i tried
export LD_PRELOAD=""  gamescope -U -f -h 2160 -r 60
export gamescope -U -f -h 2160 -r 60
export gamescope=-U -f -h 2160 -r 60

none of those work in steamos-session, any tips on how to get it running on steamos compositor plus?

**Comment by Samsagax** [comment]
What are you trying to acomplish? You can change sessions between steamos-compositor-plus and gamescooe session. But why would you nest gamescope inside steamos-compositor-plus?

**Comment by massatt212** [comment]
I have a lot of games and it would be nice not to keep entering that on command in steam launch option, I would just want compress play and game cope settings work on all games.

**Comment by Samsagax** [comment]
> I have a lot of games and it would be nice not to keep entering that on command in steam launch option, I would just want compress play and game cope settings work on all games.

But why would you want gamescope compositor if you are already using steamos-compositor-plus?

If you want to use gamescope exclusively, then you can change sessions (changing X for Wayland):
```
$ sudo systemctl disable lightdm.service
$ sudo systemctl enable gamescope@tty1.service
```
On a TTY. Then you will be using gamescope for all your games.

**Comment by alkazar** [comment]
gamescope is the successor to steamos-compositor-plus. You should only be using one or the other. I wouldn't expect gamescope to work inside a steamos-compositor-plus session.
