### ISSUE TITLE
Black Screen when launching

### ISSUE THREAD

**Issue by C0nvert** [alkazar/steamos-compositor#47]
After installing Steamos-compositor-plus from the AUR Repository, i get alwys a Blackscreen if i'm trying to start SteamOS from the Window Manager..

**Comment by alkazar** [comment]
What GPU do you have?

**Comment by C0nvert** [comment]
Tried it on different PCs
- Nvidia (GTX1080) - Main
- Intel HD Graphics 5500 - Laptop
- Inside Virtualbox

If i kill steamcompmgr it starts a Session in Big Picture (but oversized) - only on Manjaro - not "vanilla" Arch

**Comment by C0nvert** [comment]
If anyone else is having the same problem.
It's due to an updated freetype2 package (libfreetype.so.6 is missing).
Downgrading freetype2 to version 2.10.4 or updating Steam to the Beta Branch, solves the problem.

https://www.gamingonlinux.com/2021/09/steam-not-working-right-on-arch-linux-its-an-issue-with-freetype-and-theres-a-fix/page=5/
