### ISSUE TITLE
Launching non-steam games doesn't work when "Steam Play for all other titles" is enabled

### ISSUE THREAD

**Issue by tognee** [alkazar/steamos-compositor#51]
steamos-compositor-plus from aur: 1.9.4-1
os: endeavour os (arch based)

I've added a game that launches directly in full screen as a non-steam game, after hitting play it stays locked to preparing the game and doesn't show anything

I don't know how to debug the issue to see if it doesn't start at all or if it doesn't go to the foreground

Also I can't use gamescope or ChimeraOS as I have a GTX 760 and it isn't supported by both

**Comment by alkazar** [comment]
Did you turn on "Enable Steam Play for all other titles" in the settings?

There is a known issue in the Steam client: https://github.com/ValveSoftware/steam-for-linux/issues/8513

**Comment by tognee** [comment]
Yes that option is enabled

Disabling that option changes the view to the three loading bars but it still doesn't show the game

Is that the issue you linked?

**Comment by tognee** [comment]
Nevermind, trying to debug the issue I've added the -g and -b flags to the compositor, removing them shows the app correctly

so to bypass the issue temporarily you need to disable the "Enable Steam Play for all other titles" option in settings

**Comment by alkazar** [comment]
This is a Steam client issue and nothing we can do about it unfortunately.

https://github.com/ValveSoftware/steam-for-linux/issues/8503
