### ISSUE TITLE
[Feature|Question] Exit to Login Manager?

### ISSUE THREAD

**Issue by bbaserdem** [alkazar/steamos-compositor#7]
I currently do not see a way to exit to Login manager (terminate the X session) option. The only two options I have are to log out, which logs me out of steam; and turn off the computer. Currently, i switch to tty2, log in to my user and issue `killall steamos-compositor`.

Is there a way to add the option akin to 'Exit to desktop' like SteamOS has; an exit to gnome. (In this case, just shutdown the steam process, which in turn would terminate the xsession, and go back into the login manager)

I am using SDDM if it makes any difference.

**Comment by alkazar** [comment]
Unfortunately, the switch to desktop feature doesn't work outside of
SteamOS.

You can remove the `-steamos` flag to Steam in `/usr/bin/steamos-session`,
I believe this will give you some more options in the power/shutdown menu,
like shuting down Steam which should get you to the login manager. However,
this will also remove things like wifi and bluetooth configuration screens.

**Comment by hirnsushi** [comment]
For a quick workaround you can create a new .desktop file (I simply copied the steam one), fill in your command and add that to your library via SteamOS Settings "Add library shortcut".
Not pretty, but works for me :smiley:

**Comment by bbaserdem** [comment]
Seeing that this is not a compositor issue and probably can't be included from the compositor end; I will be closing this issue. Thanks for the suggestion, that seems like the sanest hack.

**Comment by bbaserdem** [comment]
If anyone is interested, drop a file named kill-steamos-compositor.desktop in ~/.local/share/applications/ and put this in;

```
[Desktop Entry]
Name=Kill Steam Compositor
Comment=Shortcut to terminate Steam compositor.
Exec=/bin/killall steamos-compositor
Icon=steam
Terminal=false
Type=Application
Categories=Network;FileTransfer;Game;
Actions=Force;

[Desktop Action Force]
Name=Force Kill Steam Compositor
Exec=/bin/killall -s SIGKILL steamos-compositor
```
