### ISSUE TITLE
system reboots before/while loading steamos

### ISSUE THREAD

**Issue by atomGit** [alkazar/steamos-compositor#8]
manjaro

after following the readme i rebooted and selected the steamos option at lightdm (which may have been too soon since the config wasn't yet created?) - the system rebooted - after coming back up, i again selected steamos at lightdm and steamos loaded with a (cool looking) image background and a message that steam was verifying files, after which the system rebooted - the 3rd reboot went exactly as the first

filtering the journald log for 'steam'...

```
7/10/19 3:21 PM	sddm	Session "/usr/share/xsessions/steamos.desktop" selected, command: "steamos-session"
7/10/19 3:21 PM	sddm-helper	Starting: "/usr/share/sddm/scripts/Xsession \"steamos-session\""
7/10/19 3:22 PM	systemd-coredump	Process 2714 (vulkandriverque) of user 1000 dumped core.

Stack trace of thread 2714:
#0  0x00007f85142d5755 raise (libc.so.6)
#1  0x00007f85142c0851 abort (libc.so.6)
#2  0x00007f85142c0727 __assert_fail_base.cold (libc.so.6)
#3  0x00007f85142ce026 __assert_fail (libc.so.6)
#4  0x000055dd63339467 n/a (/home/usr/.local/share/Steam/ubuntu12_64/vulkandriverquery)
#5  0x000055dd63320277 n/a (/home/usr/.local/share/Steam/ubuntu12_64/vulkandriverquery)
#6  0x00007f85142c1ee3 __libc_start_main (libc.so.6)
#7  0x000055dd633200ea n/a (/home/usr/.local/share/Steam/ubuntu12_64/vulkandriverquery)

7/10/19 3:22 PM	sddm-greeter	Reading from "/usr/share/xsessions/steamos.desktop"
7/10/19 3:22 PM	systemd-coredump	Process 2632 (steam) of user 1000 dumped core.

Stack trace of thread 2732:
#0  0x00000000e52179e2 n/a (/home/usr/.local/share/Steam/ubuntu12_32/libaudio.so)
#1  0x0000000000000001 n/a (n/a)

7/10/19 3:24 PM	plasmashell	KActivitiesStats( 0x555ed9bfb4b0 ) ResultModelPrivate::onResultScoreUpdated  result added: "/usr/bin/steamcompmgr.original" score: 0 last: 1562786662 first: 1562786662
7/10/19 3:24 PM	plasmashell	KActivitiesStats( 0x555ed9bfb4b0 ) ResultModelPrivate::onResultScoreUpdated  result added: "/usr/bin/steamcompmgr" score: 0 last: 1562786662 first: 1562786662
7/10/19 3:24 PM	plasmashell	KActivitiesStats( 0x555ed9bfb4b0 ) ResultModelPrivate::onResultScoreUpdated  result added: "/usr/bin/steamcompmgr.original" score: 0 last: 1562786678 first: 1562786678
7/10/19 3:24 PM	plasmashell	KActivitiesStats( 0x555ed9bfb4b0 ) ResultModelPrivate::onResultScoreUpdated  result added: "/usr/bin/steamcompmgr" score: 0 last: 1562786678 first: 1562786678
7/10/19 3:26 PM	sudo	    usr : TTY=pts/1 ; PWD=/usr/bin ; USER=root ; COMMAND=/usr/bin/mv steamcompmgr.original steamcompmgr
7/10/19 3:27 PM	sudo	    usr : TTY=pts/1 ; PWD=/usr/bin/steamos ; USER=root ; COMMAND=/usr/bin/mv set_hd_mode.sh.original set_hd_mode.sh
7/10/19 3:28 PM	systemd-coredump	Process 3924 (vulkandriverque) of user 1000 dumped core.

Stack trace of thread 3924:
#0  0x00007f421c0eb755 raise (libc.so.6)
#1  0x00007f421c0d6851 abort (libc.so.6)
#2  0x00007f421c0d6727 __assert_fail_base.cold (libc.so.6)
#3  0x00007f421c0e4026 __assert_fail (libc.so.6)
#4  0x000056543b749467 n/a (/home/usr/.local/share/Steam/ubuntu12_64/vulkandriverquery)
#5  0x000056543b730277 n/a (/home/usr/.local/share/Steam/ubuntu12_64/vulkandriverquery)
#6  0x00007f421c0d7ee3 __libc_start_main (libc.so.6)
#7  0x000056543b7300ea n/a (/home/usr/.local/share/Steam/ubuntu12_64/vulkandriverquery)

7/10/19 3:28 PM	kdeinit5	Registering ":1.132/org/ayatana/NotificationItem/steam" to system tray
7/10/19 3:28 PM	plasmashell	KActivitiesStats( 0x555ed9bfb4b0 ) ResultModelPrivate::onResultScoreUpdated  result added: "/usr/bin/steamos" score: 0 last: 1562786903 first: 1562786903
```

**Comment by alkazar** [comment]
Looks like it is dying inside a Steam provided library. Are you able to run
Steam from a regular desktop session using the command found in
/usr/bin/steamos-session? Are you able to run Steam in big picture mode at
all?

**Comment by atomGit** [comment]
i don't have a /usr/bin/steamos-session exactly - mine is /usr/bin/steamos and in it is a single excitable, set_hd_mode.sh which says...

```
#!/bin/bash

# This script attempts to set a known-good mode on a good output
```

not sure what might happen if i run that, so i didn't :)

and yes, i can run Steam in BP mode from the desktop

also, i'm using the steam-native runtime if that makes a diff

off topic ... minor little niggle you might want to make a note of - when steamos-compositor is uninstalled, it deletes the 2 files it created but doesn't rename the .original ones - will open another issue if you like

**Comment by atomGit** [comment]
couple things that might (not) help...

each time the system rebooted it did so normally - it wasn't a hard reset like if the system completely crashed

and because S-BP seemed to start normally on the 2nd attempt, but with the message that it was verifying the install, i thought maybe Steam replaced some files which is why it wouldn't load at all the 3rd time ???

also i have Steam set to run in a lower res than my desktop res

and steam was installed from the Manjaro repo - not 'flatpack', whatever that is

lastly, i'm forced to run the open-source video driver (the Nvidia driver will not work on this system (video corruption, overheat) unless it's the OEM driver which isn't available for linux)

**Comment by alkazar** [comment]
How did you install this? It sounds like you installed it manually and incorrectly since you appear to be missing key files. There is no renaming of files unless you did that yourself.

If you are using Manjaro, just install steamos-compositor-plus from the AUR.

**Comment by alkazar** [comment]
After reviewing, I think you might have followed the installation instructions for SteamOS instead of Arch Linux. Can you confirm?

**Comment by atomGit** [comment]
i don't recall for certain how i installed the compositor, but i highly suspect i followed both the Arch _and_ SteamOS instructions - when reading the instructions, it appears that each of these instructions are steps to be followed

given that i likely followed both instructions, i'd like to start with a clean system before testing further - the compositor AUR package was removed, but what might i need to clean up from running the steamos-install.sh script?

**Comment by alkazar** [comment]
You should only need to delete the following files:
/usr/bin/steamcompmgr.original
/usr/bin/steamos/set_hd_mode.sh.original

I believe what happened is you ended up running the steamos compositor built for SteamOS which didn't go so well.

I am still confused as to how you did not have `/usr/bin/steamos-session`, without that I would not expect the error that you reported.

Any ideas on how I could make the instructions clearer?

**Comment by alkazar** [comment]
Doesnt appear to be a bug in the compositor, closing.
