### ISSUE TITLE
not working on new steamos install

### ISSUE THREAD

**Issue by theoppermann** [alkazar/steamos-compositor#9]
desktop@steamos:~$ sudo sh steamos-install.sh
steamos-install.sh: 7: steamos-install.sh: function: not found

**Comment by alkazar** [comment]
Did you download the `steamos-install.sh` file? Does that file exist? Did you run the installation command listed in the instructions: `wget https://raw.githubusercontent.com/alkazar/steamos-compositor/master/steamos-install.sh && sudo sh steamos-install.sh` ?

**Comment by theoppermann** [comment]
yes
i am using this version of steamos
http://repo.steampowered.com/download/brewmaster/SteamOSDVD.iso

desktop@steamos:~$ wget
https://raw.githubusercontent.com/alkazar/steamos-compositor/master/steamos-install.sh
&& sudo sh steamos-install.sh
--2019-08-05 15:20:06--
https://raw.githubusercontent.com/alkazar/steamos-compositor/master/steamos-install.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)...
151.101.36.133
Connecting to raw.githubusercontent.com
(raw.githubusercontent.com)|151.101.36.133|:443...
connected.
HTTP request sent, awaiting response... 200 OK
Length: 641 [text/plain]
Saving to: ‘steamos-install.sh’

steamos-install.sh
100%[=======================================================================>]
    641  --.-KB/s   in 0s

2019-08-05 15:20:07 (2.41 MB/s) - ‘steamos-install.sh’ saved [641/641]

steamos-install.sh: 7: steamos-install.sh: function: not found
desktop@steamos:~$


Den man. 5. aug. 2019 kl. 14.41 skrev alkazar <notifications@github.com>:

**Comment by alkazar** [comment]
That error message seems strange. Can you open the downloaded `steamos-install.sh` file and make sure the file contents match what is in the repository in github?

**Comment by marciocr** [comment]
I had the same problem. What happens is that "sh" is a symbolic link to the dash. And scripts written to run bash are not always compatible with other terminals and vice versa.

The solution is instead of running with sh, running directly with bash.

**Comment by theoppermann** [comment]
thanks Márcio bash seams to do the trick.

sudo bash steamos-install.sh
[sudo] password for desktop:
Installation complete. Please restart the system for changes to take effect.

Den tir. 6. aug. 2019 kl. 04.17 skrev Márcio Carneiro Rodrigues <
notifications@github.com>:

**Comment by alkazar** [comment]
Thanks folks! I have updated the instructions.
